### ISSUE TITLE
Plan and communicate first OP Praise Team meeting

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/planning#118]
Date: First week of September

## Tasks:
- [ ] Make memes, @parrachia 
- [ ] Push personal invites to "key folks"
- [ ] Push invites on Discord
- [ ] Push invites on Twitter
- [ ] .. what else? 

## Questions:
Who facilitates, who takes on role as team lead?

## Who should be kept in the loop?

Everyone, ping @justi0 @brichis @EliGior @franculio @anamarija09
